"""empty message

Revision ID: 25b0df32d437
Revises: 
Create Date: 2025-06-10 02:10:45.740845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25b0df32d437'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('login', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pas', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date')
        batch_op.drop_column('pas')
        batch_op.drop_column('login')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
