"""empty message

Revision ID: 985a71116cb4
Revises: 25b0df32d437
Create Date: 2025-06-10 02:13:09.000152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '985a71116cb4'
down_revision = '25b0df32d437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
